-- Generated by tools/generate-koreader-compatibility.py; do not edit by hand.
-- This is a declaration boundary, not a claim that partial tags have full parity.
local Compatibility = {}
Compatibility.tags = {
    ["abilities"] = { status="presentation", attributes={  } },
    ["adjust"] = { status="partial", attributes={ ["ability"]=true, ["amount"]=true, ["codeword"]=true, ["crew"]=true, ["default"]=true, ["god"]=true, ["greaterthan"]=true, ["item"]=true, ["modifier"]=true, ["name"]=true, ["profession"]=true, ["ship"]=true, ["tags"]=true, ["title"]=true, ["titleval"]=true, ["value"]=true } },
    ["adjustmoney"] = { status="partial", attributes={ ["cache"]=true, ["force"]=true, ["multiply"]=true, ["name"]=true } },
    ["adventurer"] = { status="presentation", attributes={ ["gender"]=true, ["name"]=true, ["profession"]=true } },
    ["adventurers"] = { status="presentation", attributes={  } },
    ["armour"] = { status="partial", attributes={ ["bonus"]=true, ["buy"]=true, ["buytags"]=true, ["group"]=true, ["name"]=true, ["quantity"]=true, ["sell"]=true } },
    ["b"] = { status="presentation", attributes={  } },
    ["buy"] = { status="partial", attributes={ ["ability"]=true, ["bonus"]=true, ["cargo"]=true, ["crew"]=true, ["flag"]=true, ["force"]=true, ["initialcrew"]=true, ["item"]=true, ["name"]=true, ["quantity"]=true, ["shards"]=true, ["ship"]=true, ["tags"]=true, ["tool"]=true } },
    ["choice"] = { status="partial", attributes={ ["book"]=true, ["box"]=true, ["currency"]=true, ["dead"]=true, ["flee"]=true, ["god"]=true, ["item"]=true, ["pay"]=true, ["profession"]=true, ["revisit"]=true, ["sail"]=true, ["section"]=true, ["shards"]=true, ["tags"]=true } },
    ["choices"] = { status="presentation", attributes={  } },
    ["curse"] = { status="partial", attributes={ ["cumulative"]=true, ["lift"]=true, ["name"]=true } },
    ["desc"] = { status="presentation", attributes={  } },
    ["difficulty"] = { status="partial", attributes={ ["ability"]=true, ["flag"]=true, ["force"]=true, ["hidden"]=true, ["level"]=true, ["modifier"]=true, ["var"]=true } },
    ["disease"] = { status="partial", attributes={ ["name"]=true } },
    ["effect"] = { status="partial", attributes={ ["ability"]=true, ["bonus"]=true, ["description"]=true, ["divide"]=true, ["target"]=true, ["text"]=true, ["type"]=true, ["uses"]=true, ["verb"]=true } },
    ["else"] = { status="partial", attributes={  } },
    ["elseif"] = { status="partial", attributes={ ["codeword"]=true, ["crew"]=true, ["equals"]=true, ["god"]=true, ["hidden"]=true, ["item"]=true, ["lessthan"]=true, ["profession"]=true, ["ship"]=true, ["ticks"]=true, ["title"]=true, ["var"]=true, ["weapon"]=true } },
    ["exclude"] = { status="missing", attributes={ ["bonus"]=true, ["item"]=true, ["reason"]=true, ["tags"]=true } },
    ["extrachoice"] = { status="missing", attributes={ ["atbook"]=true, ["atsection"]=true, ["book"]=true, ["key"]=true, ["remove"]=true, ["section"]=true, ["tag"]=true, ["text"]=true } },
    ["failure"] = { status="partial", attributes={ ["book"]=true, ["section"]=true, ["var"]=true } },
    ["field"] = { status="missing", attributes={ ["label"]=true, ["name"]=true, ["text"]=true } },
    ["fight"] = { status="partial", attributes={ ["abilitydamaged"]=true, ["attackdice"]=true, ["attacks"]=true, ["combat"]=true, ["defence"]=true, ["flee"]=true, ["group"]=true, ["modifiers"]=true, ["name"]=true, ["playerdefence"]=true, ["playerfirst"]=true, ["predamage"]=true, ["stamina"]=true, ["staminalost"]=true, ["usecache"]=true } },
    ["fightdamage"] = { status="partial", attributes={ ["type"]=true } },
    ["fightround"] = { status="partial", attributes={ ["pre"]=true } },
    ["flee"] = { status="partial", attributes={  } },
    ["gain"] = { status="partial", attributes={ ["ability"]=true, ["amount"]=true, ["blessing"]=true, ["codeword"]=true, ["crew"]=true, ["flag"]=true, ["force"]=true, ["hidden"]=true, ["price"]=true, ["shards"]=true, ["title"]=true } },
    ["gold"] = { status="presentation", attributes={ ["amount"]=true } },
    ["goto"] = { status="partial", attributes={ ["book"]=true, ["dead"]=true, ["force"]=true, ["hidden"]=true, ["price"]=true, ["sail"]=true, ["section"]=true, ["visit"]=true } },
    ["group"] = { status="partial", attributes={ ["force"]=true } },
    ["header"] = { status="presentation", attributes={ ["header1"]=true, ["header2"]=true, ["header3"]=true, ["type"]=true } },
    ["i"] = { status="presentation", attributes={  } },
    ["if"] = { status="partial", attributes={ ["ability"]=true, ["armour"]=true, ["blessing"]=true, ["bonus"]=true, ["book"]=true, ["cache"]=true, ["cargo"]=true, ["codeword"]=true, ["crew"]=true, ["curse"]=true, ["dead"]=true, ["dice"]=true, ["disease"]=true, ["docked"]=true, ["equals"]=true, ["gender"]=true, ["god"]=true, ["greaterthan"]=true, ["group"]=true, ["item"]=true, ["lessthan"]=true, ["modifier"]=true, ["name"]=true, ["not"]=true, ["poison"]=true, ["profession"]=true, ["resurrection"]=true, ["safeaddgod"]=true, ["safeaddgodd"]=true, ["shards"]=true, ["ship"]=true, ["tags"]=true, ["ticks"]=true, ["title"]=true, ["tool"]=true, ["using"]=true, ["var"]=true, ["weapon"]=true } },
    ["image"] = { status="implemented", attributes={ ["book"]=true, ["file"]=true, ["title"]=true } },
    ["include"] = { status="missing", attributes={ ["armour"]=true, ["weapon"]=true } },
    ["item"] = { status="partial", attributes={ ["buy"]=true, ["buytags"]=true, ["flag"]=true, ["force"]=true, ["group"]=true, ["hidden"]=true, ["name"]=true, ["quantity"]=true, ["replace"]=true, ["sell"]=true, ["tags"]=true, ["verb"]=true } },
    ["itemcache"] = { status="partial", attributes={ ["itemlimit"]=true, ["max"]=true, ["name"]=true, ["text"]=true } },
    ["items"] = { status="presentation", attributes={ ["group"]=true, ["limit"]=true } },
    ["lose"] = { status="partial", attributes={ ["ability"]=true, ["amount"]=true, ["armour"]=true, ["blessing"]=true, ["bonus"]=true, ["cache"]=true, ["cargo"]=true, ["chance"]=true, ["codeword"]=true, ["crew"]=true, ["curse"]=true, ["disease"]=true, ["fatal"]=true, ["flag"]=true, ["force"]=true, ["god"]=true, ["group"]=true, ["hidden"]=true, ["item"]=true, ["itemat"]=true, ["items"]=true, ["multiple"]=true, ["poison"]=true, ["price"]=true, ["resurrection"]=true, ["shards"]=true, ["ship"]=true, ["stamina"]=true, ["staminato"]=true, ["tags"]=true, ["title"]=true, ["using"]=true, ["weapon"]=true } },
    ["market"] = { status="partial", attributes={ ["buy"]=true, ["currency"]=true, ["sell"]=true } },
    ["moneycache"] = { status="partial", attributes={ ["max"]=true, ["multiples"]=true, ["name"]=true, ["text"]=true, ["withdrawcharge"]=true } },
    ["outcome"] = { status="partial", attributes={ ["blessing"]=true, ["book"]=true, ["codeword"]=true, ["flag"]=true, ["range"]=true, ["section"]=true, ["var"]=true } },
    ["outcomes"] = { status="partial", attributes={ ["flag"]=true, ["var"]=true } },
    ["p"] = { status="presentation", attributes={  } },
    ["poison"] = { status="partial", attributes={ ["name"]=true } },
    ["price"] = { status="missing", attributes={ ["flag"]=true, ["shards"]=true } },
    ["profession"] = { status="presentation", attributes={ ["name"]=true } },
    ["random"] = { status="partial", attributes={ ["dice"]=true, ["flag"]=true, ["force"]=true, ["type"]=true, ["var"]=true } },
    ["rank"] = { status="presentation", attributes={ ["amount"]=true } },
    ["rankcheck"] = { status="partial", attributes={ ["add"]=true, ["dice"]=true } },
    ["reroll"] = { status="partial", attributes={  } },
    ["rest"] = { status="partial", attributes={ ["hidden"]=true, ["shards"]=true, ["stamina"]=true } },
    ["resurrection"] = { status="partial", attributes={ ["book"]=true, ["flag"]=true, ["god"]=true, ["hidden"]=true, ["section"]=true, ["shards"]=true, ["supplemental"]=true, ["text"]=true } },
    ["return"] = { status="partial", attributes={ ["force"]=true } },
    ["section"] = { status="presentation", attributes={ ["boxes"]=true, ["dock"]=true, ["image"]=true, ["name"]=true, ["profession"]=true, ["start"]=true, ["tag"]=true, ["todock"]=true } },
    ["sectionview"] = { status="missing", attributes={ ["random"]=true, ["title"]=true } },
    ["sell"] = { status="partial", attributes={ ["cargo"]=true, ["item"]=true, ["price"]=true, ["quantity"]=true, ["shards"]=true } },
    ["set"] = { status="partial", attributes={ ["cache"]=true, ["codeword"]=true, ["dock"]=true, ["force"]=true, ["hidden"]=true, ["item"]=true, ["modifier"]=true, ["tags"]=true, ["value"]=true, ["var"]=true, ["weapon"]=true } },
    ["sold"] = { status="missing", attributes={ ["item"]=true, ["tags"]=true } },
    ["stamina"] = { status="presentation", attributes={ ["amount"]=true } },
    ["starting"] = { status="presentation", attributes={  } },
    ["success"] = { status="partial", attributes={ ["ability"]=true, ["book"]=true, ["section"]=true, ["var"]=true } },
    ["text"] = { status="presentation", attributes={  } },
    ["tick"] = { status="partial", attributes={ ["ability"]=true, ["addbonus"]=true, ["addtag"]=true, ["amount"]=true, ["blessing"]=true, ["bonus"]=true, ["cache"]=true, ["cargo"]=true, ["codeword"]=true, ["count"]=true, ["crew"]=true, ["effect"]=true, ["flag"]=true, ["force"]=true, ["god"]=true, ["hidden"]=true, ["item"]=true, ["name"]=true, ["permanent"]=true, ["price"]=true, ["profession"]=true, ["quantity"]=true, ["removetag"]=true, ["shards"]=true, ["special"]=true, ["tag"]=true, ["tags"]=true, ["titaladjust"]=true, ["title"]=true, ["titleadjust"]=true, ["titlepattern"]=true, ["titlevalue"]=true, ["using"]=true, ["weapon"]=true } },
    ["tool"] = { status="partial", attributes={ ["ability"]=true, ["bonus"]=true, ["buy"]=true, ["flag"]=true, ["group"]=true, ["name"]=true, ["replace"]=true, ["sell"]=true } },
    ["trade"] = { status="partial", attributes={ ["buy"]=true, ["cargo"]=true, ["initialcrew"]=true, ["name"]=true, ["quantity"]=true, ["sell"]=true, ["ship"]=true } },
    ["training"] = { status="partial", attributes={ ["ability"]=true, ["add"]=true, ["dice"]=true, ["var"]=true } },
    ["transfer"] = { status="partial", attributes={ ["armour"]=true, ["bonus"]=true, ["force"]=true, ["from"]=true, ["hidden"]=true, ["item"]=true, ["limit"]=true, ["price"]=true, ["shards"]=true, ["to"]=true, ["weapon"]=true, ["xarmour"]=true, ["xgroup"]=true, ["xitem"]=true } },
    ["weapon"] = { status="partial", attributes={ ["bonus"]=true, ["buy"]=true, ["buytags"]=true, ["flag"]=true, ["force"]=true, ["group"]=true, ["name"]=true, ["profession"]=true, ["quantity"]=true, ["replace"]=true, ["sell"]=true, ["tags"]=true } },
    ["while"] = { status="partial", attributes={ ["var"]=true } },
}

local function visit(node, source)
    if type(node) ~= "table" then return end
    local declaration = Compatibility.tags[node.name]
    if not declaration then
        error(string.format("Unsupported XML element <%s> in %s", tostring(node.name), source or "section"))
    end
    if declaration.status ~= "presentation" then
        for name in pairs(node.attr or {}) do
            if not declaration.attributes[name] then
                error(string.format("Unsupported attribute '%s' on <%s> in %s", name, node.name, source or "section"))
            end
        end
    end
    for _, child in ipairs(node.children or {}) do visit(child, source) end
end

function Compatibility.assert_declared(root, source)
    visit(root, source)
end

return Compatibility
