#!/usr/bin/env python3
"""Generate the checked-in KOReader XML census and runtime declarations."""
from __future__ import annotations

import argparse
import json
import xml.etree.ElementTree as ET
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
JSON_PATH = ROOT / "docs" / "koreader-content-census.json"
LUA_PATH = ROOT / "plugins" / "jafl.koplugin" / "content" / "compatibility.lua"

PRESENTATION = {
    "abilities", "adventurer", "adventurers", "b", "choices", "desc",
    "gold", "h1", "h2", "h3", "h4", "header", "i", "items", "p", "profession",
    "rank", "section", "stamina", "starting", "table", "td", "text", "tr",
}
MISSING = {"exclude", "field", "include", "price", "sectionview", "sold"}
IMPLEMENTED = {"image"}


def lua_quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


tags: Counter[str] = Counter()
attributes: dict[str, Counter[str]] = defaultdict(Counter)
files = []
for book in range(1, 7):
    for path in sorted((ROOT / f"book{book}").glob("*.xml")):
        files.append(path)
        for element in ET.parse(path).iter():
            tag = element.tag.lower()
            tags[tag] += 1
            attributes[tag].update(name.lower() for name in element.attrib)

payload = {
    "schema": 1,
    "scope": "book1 through book6 XML",
    "files": len(files),
    "elements": sum(tags.values()),
    "tags": {
        tag: {
            "count": tags[tag],
            "support": "presentation" if tag in PRESENTATION else "missing" if tag in MISSING else "implemented" if tag in IMPLEMENTED else "partial",
            "attributes": dict(sorted(attributes[tag].items())),
        }
        for tag in sorted(tags)
    },
}
json_content = json.dumps(payload, indent=2, sort_keys=True) + "\n"

lines = [
    "-- Generated by tools/generate-koreader-compatibility.py; do not edit by hand.",
    "-- This is a declaration boundary, not a claim that partial tags have full parity.",
    "local Compatibility = {}",
    "Compatibility.tags = {",
]
for tag in sorted(tags):
    status = "presentation" if tag in PRESENTATION else "missing" if tag in MISSING else "implemented" if tag in IMPLEMENTED else "partial"
    attrs = ", ".join(f"[{lua_quote(name)}]=true" for name in sorted(attributes[tag]))
    lines.append(f"    [{lua_quote(tag)}] = {{ status={lua_quote(status)}, attributes={{ {attrs} }} }},")
lines += [
    "}",
    "",
    "local function visit(node, source)",
    "    if type(node) ~= \"table\" then return end",
    "    local declaration = Compatibility.tags[node.name]",
    "    if not declaration then",
    "        error(string.format(\"Unsupported XML element <%s> in %s\", tostring(node.name), source or \"section\"))",
    "    end",
    "    if declaration.status ~= \"presentation\" then",
    "        for name in pairs(node.attr or {}) do",
    "            if not declaration.attributes[name] then",
    "                error(string.format(\"Unsupported attribute '%s' on <%s> in %s\", name, node.name, source or \"section\"))",
    "            end",
    "        end",
    "    end",
    "    for _, child in ipairs(node.children or {}) do visit(child, source) end",
    "end",
    "",
    "function Compatibility.assert_declared(root, source)",
    "    visit(root, source)",
    "end",
    "",
    "return Compatibility",
]
lua_content = "\n".join(lines) + "\n"

parser = argparse.ArgumentParser()
parser.add_argument("--check", action="store_true", help="fail if checked-in generated files are stale")
args = parser.parse_args()
outputs = ((JSON_PATH, json_content), (LUA_PATH, lua_content))
if args.check:
    stale = [str(path.relative_to(ROOT)) for path, content in outputs if not path.is_file() or path.read_text() != content]
    if stale:
        parser.error("stale generated files: " + ", ".join(stale))
    print("KOReader compatibility census and declarations are up to date")
else:
    for path, content in outputs:
        path.write_text(content)
    print(f"Wrote {JSON_PATH.relative_to(ROOT)} and {LUA_PATH.relative_to(ROOT)}")
